apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eventified-backend-ingress
  namespace: eventified
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: cloud.kosickaakademia.sk
      http:
        paths:
          - path: /eventified/api
            pathType: Prefix
            backend:
              service:
                name: eventified-backend-service
                port:
                  number: 8080