apiVersion: v1
kind: Service
metadata:
  name: eventified-backend-service
  namespace: eventified
  labels:
    app: eventified-backend
spec:
  selector:
    app: eventified-backend
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  type: ClusterIP
